name: Auto Update Website with New Image

on:
  push:
    paths:
      - 'images/*'   # This means it will trigger whenever a file is added/modified in the 'images' folder

jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update HTML with new image
        run: |
          # Adds the image URLs to the HTML file
          echo '<img src="images/$(basename $GITHUB_SHA).jpg" alt="New Image" />' >> index.html

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Added new image to gallery"
          git push
